# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=256)),
                ('from_address', models.CharField(max_length=256, verbose_name='From')),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('body', models.TextField()),
                ('html_body', models.TextField(blank=True, verbose_name='HTML body')),
                ('date_sent', models.DateTimeField()),
                ('delivery_successful', models.BooleanField()),
                ('error_message', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'verbose_name': 'Email message',
                'verbose_name_plural': 'Email messages',
                'permissions': [('can_resend_email', 'Can resend email')],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('nonce', models.CharField(blank=True, max_length=64)),
                ('blacklist', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
            },
        ),
    ]
