# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_blacklist_recipient', 'Can blacklist recipients'), ('can_whitelist_recipient', 'Can whitelist recipients')], 'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
    ]
