# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 06:52
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gfklookupwidget.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('summary', ckeditor.fields.RichTextField(blank=True, verbose_name='Summary')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('index', models.PositiveIntegerField(verbose_name='Index')),
                ('question_id', gfklookupwidget.fields.GfkLookupField(verbose_name='Question ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizard.Assignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Question type')),
            ],
            options={
                'ordering': ['index'],
                'verbose_name': 'Assignment question',
                'verbose_name_plural': 'Assignment questions',
            },
        ),
        migrations.CreateModel(
            name='FreeResponseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('value', models.CharField(max_length=255, verbose_name='Answer value')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Free response answer',
                'verbose_name_plural': 'Free response answers',
            },
        ),
        migrations.CreateModel(
            name='FreeResponseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('point_value', models.PositiveIntegerField(verbose_name='Point value')),
                ('explanation', ckeditor.fields.RichTextField(verbose_name='Explanation')),
                ('html', ckeditor.fields.RichTextField(verbose_name='Question text')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Free response question',
                'verbose_name_plural': 'Free response questions',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('value', ckeditor.fields.RichTextField(verbose_name='Answer text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Multiple choice answer',
                'verbose_name_plural': 'Multiple choice answers',
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('point_value', models.PositiveIntegerField(verbose_name='Point value')),
                ('explanation', ckeditor.fields.RichTextField(verbose_name='Explanation')),
                ('html', ckeditor.fields.RichTextField(verbose_name='Question text')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Multiple choice question',
                'verbose_name_plural': 'Multiple choice questions',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('pretty_name', ckeditor.fields.RichTextField(blank=True, verbose_name='Pretty name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizard.MultipleChoiceQuestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='freeresponseanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizard.FreeResponseQuestion', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizard.School', verbose_name='School'),
        ),
        migrations.AlterUniqueTogether(
            name='freeresponseanswer',
            unique_together=set([('question', 'value')]),
        ),
    ]
