# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizard', '0002_auto_20170811_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeresponseanswer',
            name='case_sensitive',
            field=models.BooleanField(default=True),
        ),
    ]
