---

ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_ssh_private_key_file: "keys/production.pem"


is_production: true

app_repository_version: "master"

app_debug: "False"
app_template_debug: "False"

app_admins:
  - ["'Zachary Mott'", "'zach.mott@gmail.com'"]

# Used to configure both 'server_name' nginx directive and
# local_settings.ALLOWED_HOSTS Django configuration parameter.
app_nginx_server_names:
  - "quizwhiz.io"

app_db_name: "quizwhiz_django"
app_db_host: "localhost"
app_db_password: "{{ vault_app_db_password }}"

app_queue_prefix: "'quizwhiz-'"

group_extra_settings:
  - {key: 'SECRET_KEY', value: "{{ vault_django_secret_key }}"}
  - {key: 'EMAIL_HOST_USER', value: "{{ vault_aws_ses_username }}"}
  - {key: 'EMAIL_HOST_PASSWORD', value: "{{ vault_aws_ses_password }}"}
  - {key: 'AWS_ACCESS_KEY_ID', value: "{{ vault_aws_access_key_id }}"}
  - {key: 'AWS_SECRET_ACCESS_KEY', value: "{{ vault_aws_secret_access_key }}"}
  - {key: 'AWS_S3_PUBLIC_URL', value: "'//cdn.quizwhiz.io'"}
  - {key: 'MEDIA_URL', value: "AWS_S3_PUBLIC_URL + '/'"}
  - {key: 'CELERY_BROKER_TRANSPORT_OPTIONS', value: "{
      'region': 'us-west-2',
      'queue_name_prefix': {{ app_queue_prefix }}
    }"}
  - {key: 'CELERY_RESULT_BACKEND', value: "'django-db'"}

group_apt_dependencies: []
group_supervisor_tasks: []

...